### PR TITLE
Removes font-weight notation

### PR DESCRIPTION
**Pull request by abea**
If we're using a weight function then we shouldn't be expecting numeric here.

### CODE REVIEW

**Comment by abea** [comment]
How about we switch it to only a `warning` severity? If our internal practice is not to use numeric font-weights (instead using the function) then having a rule that font weight should be numeric isn't doing anything for us.

**Comment by austinstarin** [comment]
One other recommendation would be change the function name `get-weight()`.

**Comment by abea** [comment]
Would that solve the issue?

**Comment by bgantick** [comment]
Changing the function name wouldn't solve the issue.

**Comment by abea** [comment]
So yeah, I think we need to remove the rule or switch it to a warning and live with those. Once the stylelint update happens that could be changed.

**Pull request merged**
